# Generated by Django 5.1.1 on 2024-09-21 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria', max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da cesta', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da cesta', null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço da cesta', max_digits=10, verbose_name='Preço')),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('M', 'Médio'), ('P', 'Premium')], default='B', help_text='Nível da cesta', max_length=1, verbose_name='Nível')),
            ],
        ),
        migrations.CreateModel(
            name='Padaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da padaria', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da padaria', null=True, verbose_name='Descrição')),
                ('cidade', models.CharField(help_text='Cidade da padaria', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Estado da padaria', max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True, help_text='Data de início da assinatura', verbose_name='Data de início')),
                ('observacao', models.TextField(blank=True, help_text='Observação da assinatura', null=True, verbose_name='Observação')),
                ('user', models.OneToOneField(help_text='Usuário da assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('cesta', models.OneToOneField(help_text='Cesta da assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='padarias.cesta', verbose_name='Cesta')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(help_text='Rua do endereço', max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(help_text='Número do endereço', max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, help_text='Complemento do endereço', max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, help_text='Bairro do endereço', max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(help_text='Cidade do endereço', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='Estado do endereço', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(help_text='CEP do endereço', max_length=8, verbose_name='CEP')),
                ('padaria', models.OneToOneField(help_text='Padaria do endereço', on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='padarias.padaria', verbose_name='Padaria')),
            ],
        ),
        migrations.CreateModel(
            name='PadariaCesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cesta', models.ForeignKey(help_text='Cesta da padaria', on_delete=django.db.models.deletion.CASCADE, related_name='padaria_cestas', to='padarias.cesta', verbose_name='Cesta')),
                ('padaria', models.ForeignKey(help_text='Padaria da cesta', on_delete=django.db.models.deletion.CASCADE, related_name='padaria_cestas', to='padarias.padaria', verbose_name='Padaria')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do produto', null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10, verbose_name='Preço')),
                ('categoria', models.ForeignKey(help_text='Categoria do produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='padarias.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='CestaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cesta', models.ForeignKey(help_text='Cesta do produto', on_delete=django.db.models.deletion.CASCADE, related_name='cesta_produtos', to='padarias.cesta', verbose_name='Cesta')),
                ('produto', models.ForeignKey(help_text='Produto da cesta', on_delete=django.db.models.deletion.CASCADE, related_name='cesta_produtos', to='padarias.produto', verbose_name='Produto')),
            ],
        ),
    ]
