volumes:
  db_data: {}

services:
  meubloguinho:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: meubanquinho 
      WORDPRESS_DB_USER: wordpress 
      WORDPRESS_DB_PASSWORD: wordpress 
      WORDPRESS_DB_NAME: wordpress 
    depends_on:
      - meubanquinho
    ports:
      - 8080:80
  meubanquinho:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql